### ISSUE TITLE
send_heart_beat function undefined

### ISSUE THREAD

**Issue by jahrome** [OpenSourceEBike/EBike_EScooter_modular_DIY#2]
Hi,
Looking at the code, I was unable to find the definition of send_heart_beat() in vesc.py as used here for example:
ebike_bafang_m500/main.py:191:        vesc.send_heart_beat()
Am I missing something ?
Thanks in advance,
Jerome

**Comment by casainho** [comment]
Hi.

Yes, I removed send_heart_beat() as I found it is not needed to send that heart beat to VESC, because on every received command, VESC will consider it also an heart beat. And I just keep sending either the motor current or the motor speed.

The most updated firmware is the one for FiidoQ1S, take that as reference: https://github.com/OpenSourceEBike/EBike_EScooter_modular_DIY/tree/main/diy_main_board/firmware/escooter_fiido_q1_s

**Comment by jahrome** [comment]
Very clear, thanks for the feedback !
